project:
  type: website

website:
  title: "Gonzalo Jaimovitch"
  back-to-top-navigation: true
  navbar:
    tools:
      - icon: twitter
        href: https://twitter.com/gonzalojlopez
      - icon: github
        href: https://github.com/gonzalojaimovitch
      - icon: linkedin
        href: https://linkedin.com/in/gonzalojai


format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true

execute:
  freeze: auto



